### ISSUE TITLE
nightly is stuck at 2017-06-28

### ISSUE THREAD

**Issue by wanderer** [AssemblyScript/wabt.js#1]
nightly is stuck at 2017-06-28 and this version of wabt has some bugs (can't parse the current syntax for call_indirect)

**Comment by dcodeIO** [comment]
There are no automatic builds yet. I just always planned to do this... maybe now is the time.

**Comment by dcodeIO** [comment]
Once [this PR](https://github.com/WebAssembly/wabt/pull/739) has landed, it should theoretically build something working again.

**Comment by dcodeIO** [comment]
There's a `1.0.0` on npm and the bot will build nightlies now.
