### ISSUE TITLE
is `utf-16le` necessary for texte decoder?

### ISSUE THREAD

**Issue by Sharpiro** [AssemblyScript/wabt.js#10]
Is it feasible to change from `TextDecoder("utf-16le")` to `TextDecoder()`?  I just want to find out if this is a feasible change as it was necessary to allow running with [deno](https://github.com/denoland/deno) 

It worked for my use cases.  But if this a required parameter, I can look into adding support for it in Deno.

https://github.com/Sharpiro/wabt.js/compare/a71274e6ffbd38b58a0b6a2ea84c80336bc9c4a6...Sharpiro:9ea629b1c31f80c70efdf9d01b489274beb0ddb1

**Comment by dcodeIO** [comment]
This one as well does appear to be either part of [WABT's post-JS code](https://github.com/WebAssembly/wabt/blob/master/src/wabt.post.js) or produced by [Emscripten](https://github.com/emscripten-core/emscripten) during compilation to JS.

**Comment by dcodeIO** [comment]
Closing this issue as it seems this must be handled upstream :)
