### ISSUE TITLE
Documenting the undocumented features

### ISSUE THREAD

**Issue by carlsmith** [AssemblyScript/wabt.js#12]
There are a number of undocumented features in the API docs. I looked through the WABT README, which didn't explain them either, and there does not seem to be any other documentation. There are also one or two places where docstrings exist, but could be clearer.

### Default Options

Is it true that every option within all four of the options objects (`WasmFeatures`, `ReadWasmOptions`, `ToTextOptions` and `ToBinaryOptions`) default to `false` (at least currently)?

### WasmModule

The `WasmModule` has a few methods, `resolveNames`, `generateNames` and `applyNames` which have docstrings, but it's not clear what these methods are used for. Are they specific to binaryen?

### ToTextOptions

The `ToTextOptions` hash has two undocumented properties, `foldExprs` and `inlineExport`. I'm assuming that `{foldExprs: true}` enables S-expressions, and `{inlineExport: true}` enables inlining export declarations, in the generated output??

### ToBinaryOptions

The `ToBinaryOptions` hash has four undocumented properties. The `log` property <strike>presumably</strike> determines whether a log is generated.

I couldn't work out what `canonicalize_lebs` or `write_debug_names` are for. Also, `relocatable` was a bit confusing to me, considering how WebAssembly abstracts memory. Adding a link here and there that explains the purpose of these features would be helpful.

### Personal Bit

My own ignorance is bound to contribute to some of the misunderstanding here, but there should be enough information in the docs for somebody to at least figure out what they need to look into. For example, I googled (and binged) *lebs*, *wabt lebs*, *wasm lebs*, *emscripten lebs* and *binaryen lebs*, and still don't know what *lebs* (or *LEBs*) are.

If we can gather the missing bits of information here, I'd be happy to update the README. I just need to understand the features myself first.

I'm not in urgent need of any of this information personally. I just like the library, and the README has been like that for ages, so it seemed worth trying to fix. Thanks.

**Comment by carlsmith** [comment]
Update: I found the docs for the toolkit's command line flags, which has made everything a lot clearer.

**Comment by dcodeIO** [comment]
Note that this repository is just a buildbot for the [original repo](https://github.com/WebAssembly/wabt), and questions are better directed to the original authors of WABT. However, these descriptions look fine and I'd be happy to merge a PR improving both the README and .d.ts docs :)

**Comment by carlsmith** [comment]
Thank you. I'll keep the repos in mind in future, and will make a PR soon. Much appreciated.
