### ISSUE TITLE
Nightly not updated for ~2 weeks

### ISSUE THREAD

**Issue by RReverser** [AssemblyScript/wabt.js#13]
We're waiting for a wabt.js update to resolve https://github.com/GoogleChromeLabs/wasm-feature-detect/issues/22.

Upstream WABT has already updated to include SIMD renumbering, but it appears that wabt.js buildbot has not published any new nightlies since (for 2 weeks now).

Not sure if related, but latest CI run appears to have had errors as well: https://travis-ci.org/github/AssemblyScript/wabt.js

**Comment by dcodeIO** [comment]
There are new latest and nightly releases now. Was a problem with the fixtures used for testing that needed to be updated.

**Comment by RReverser** [comment]
Thanks!
