### ISSUE TITLE
--enable-gc and/or --enable-all

### ISSUE THREAD

**Issue by Horcrux7** [AssemblyScript/wabt.js#17]
The Wabt Tools implements the command line options: `--enable-gc` and `--enable-all`. Is there an equivalent WasmFeature parameter in wabt.js?

**Comment by dcodeIO** [comment]
The respective feature flag [exists now](https://github.com/AssemblyScript/wabt.js/blob/3f9d4639e73b1485db4e8f5b2abdf3787f13c7d8/index.d.ts#L26), and should become available with the next successful build.

**Comment by dcodeIO** [comment]
Should be on npm now, v1.0.17.
