### ISSUE TITLE
Where are the sources ?

### ISSUE THREAD

**Issue by guimard** [AssemblyScript/wabt.js#20]
Hi,

I'd like to rebuild wabt.js from sources but this directory only contains a webpacked file. Could you give me the link to the source directory ?

Cheers,

Xavier (yadd)

**Comment by Horcrux7** [comment]
The sources are linked to the WABT project. https://github.com/WebAssembly/wabt

**Comment by guimard** [comment]
Thanks, but I didn't find the way to build it from [wabt](https://github.com/WebAssembly/wabt). What is the build target ?

**Comment by Horcrux7** [comment]
I think it is build with emscripten SDK. You can take a look into the actions to see details. I have no idea how you can do it self.

**Comment by Horcrux7** [comment]
Or you look into the yaml file https://github.com/AssemblyScript/wabt.js/blob/master/.github/workflows/build.yml
