### ISSUE TITLE
Version 1.0.21

### ISSUE THREAD

**Issue by Horcrux7** [AssemblyScript/wabt.js#22]
The build has been failing for months. In the meantime, version 1.0.21 is available. Is it possible to fix this?

**Comment by dcodeIO** [comment]
Whoops, yep, we should certainly fix that.

**Comment by dcodeIO** [comment]
Fixed the workflow meanwhile. If everything works out, there should a be a new release around 0 UTC.

**Comment by dcodeIO** [comment]
Seems it worked :)
