### ISSUE TITLE
WasmFeatures "reference_types" does not work anymore

### ISSUE THREAD

**Issue by Horcrux7** [AssemblyScript/wabt.js#26]
Reference Types are now default in WABT. But in the nightly build of wabt.js it does not work anymore for parseWat. I receive the follow error multiple times:

```
test.wat:41:22: error: value type not allowed: externref
        (param $this externref)
                     ^^^^^^^^^
```

* It work with a nightly build from wat2wasm.
* It work latest version 1.024 of wabt.js.
* But it does not work with wabt@nightly

My code look like:

```
#!/usr/bin/env node

var fs = require('fs');
require("wabt")().then(wabt => {

var filename = 'test.wat';
var text = fs.readFileSync(filename, "utf8");

var features = {'sat_float_to_int':true, 'sign_extension':true, 'exceptions':true, 'reference_types':true, 'gc':true};
var wasm = wabt.parseWat(filename, text, features);
...
});
```

**Comment by marcusb** [comment]
Should be fixed by https://github.com/AssemblyScript/wabt.js/pull/38
