### ISSUE TITLE
Provide ESM version of package

### ISSUE THREAD

**Issue by dvtate** [AssemblyScript/wabt.js#33]
Additionally you should make it so that the typings of in .d.ts are publically accessible (at least the interfaces which are compile-time only)

**Comment by dvtate** [comment]
This is no longer an issue for me as typescript has an `esModuleInterop` flag which allows commonjs modules to work with esm projects and node.js has `createRequire`, both of which do not require use of the dynamic, async imports which would require essentially rewriting a project that already exists.

However because @AssemblyScript is owner for both of these repositories I'd honestly expect more consistency in the packaging but that's not the case https://github.com/AssemblyScript/binaryen.js/issues/63

**Comment by AsynchronousAI** [comment]
> This is no longer an issue for me as typescript has an `esModuleInterop` flag which allows commonjs modules to work with esm projects and node.js has `createRequire`, both of which do not require use of the dynamic, async imports which would require essentially rewriting a project that already exists.
> 
> However because @AssemblyScript is owner for both of these repositories I'd honestly expect more consistency in the packaging but that's not the case [AssemblyScript/binaryen.js#63](https://github.com/AssemblyScript/binaryen.js/issues/63)

I know it has been a while but:
```
4 | const binaryen = requireFromThisFile('binaryen');
                     ^
TypeError: require() async module "/Users/aaravs/Desktop/obsidian/node_modules/binaryen/index.js" is unsupported. use "await import()" instead.
```
