### ISSUE TITLE
wasm2c dependency on libcrypto-1_1-x64.dll

### ISSUE THREAD

**Issue by ArcaneEngineer** [AssemblyScript/wabt.js#46]
The DLL can be found in OpenSSL 1.1.1, available [here](https://wiki.overbyte.eu/wiki/index.php/ICS_Download). My wasm2c crashed hard on trying to run until I gave it access to this DLL (cannot be registered via `regsvr32`). Add to path or put it alongside WABT's binaries works. Obviously not a default installed DLL under Windows.

Probably should be listed as a dependency in the README? -- or the dep should be eliminated if not absolutely key.

**Comment by dcodeIO** [comment]
Seems this concerns the upstream repo here: https://github.com/WebAssembly/wabt
