### ISSUE TITLE
Figure out why builds sometimes work and most of the time don't

### ISSUE THREAD

**Issue by dcodeIO** [AssemblyScript/wabt.js#5]
Appears the bot is occasionally publishing after successful builds, but most of the time it fails with something like

```
Building nightly v1.0.11-nightly.20190906 ...
-- Looking for alloca.h
-- Looking for alloca.h - not found
-- Looking for unistd.h
-- Looking for unistd.h - not found
-- Looking for snprintf
-- Looking for snprintf - not found
-- Looking for sysconf
-- Looking for sysconf - not found
-- Looking for strcasecmp
-- Looking for strcasecmp - not found
-- Looking for sys/types.h
-- Looking for sys/types.h - not found
-- Looking for stdint.h
-- Looking for stdint.h - not found
-- Looking for stddef.h
-- Looking for stddef.h - not found
-- Check size of ssize_t
-- Check size of ssize_t - failed
-- Check size of size_t
-- Check size of size_t - failed
-- Configuring done
-- Generating done
-- Build files have been written to: /home/travis/build/AssemblyScript/wabt.js/wabt
Scanning dependencies of target wabt
[  4%] Building CXX object CMakeFiles/wabt.dir/src/apply-names.cc.o
[  4%] Building CXX object CMakeFiles/wabt.dir/src/binary.cc.o
In file included from In file included from /home/travis/build/AssemblyScript/wabt.js/wabt/src/binary.cc:17:
In file included from /home/travis/build/AssemblyScript/wabt.js/wabt/src/binary.h:20:
In file included from /home/travis/build/AssemblyScript/wabt.js/wabt/src/common.h:33:
/home/travis/build/AssemblyScript/wabt.js/wabt/config.h:270:2: error: no snprintf
#error no snprintf
...
```

One reason could be that the build cache (ccache) becomes corrupted somehow, another could be that the [build script](https://github.com/AssemblyScript/wabt.js/blob/master/.travis.yml) is doing something wrong.

**Comment by dcodeIO** [comment]
On a closer look it seems that the build started failing consistently with the error above after June 25 and neither clearing ccache nor updating to [make emscripten-release](https://github.com/AssemblyScript/wabt.js/blob/master/.travis.yml#L76) seems to fix it. @binji @kripken any idea what's happening there? Could be unreleated to wabt, related to emscripten, or unrelated to both and be a travis thing. Hrm.

**Comment by kripken** [comment]
How does wabt look for snprintf in emscripten?

**Comment by dcodeIO** [comment]
All I know is that [this](https://github.com/WebAssembly/wabt/blob/master/src/config.h.in#L270) happens, which seems to be the first occasion where it detects that the configure script wasn't able to find ... well ... anything. Also not reproducible on any other machine than here in Travis.

I've changed the build to utilize the Emscripten docker image now instead of compiling from source. Hope that keeps working :)
