### ISSUE TITLE
Is it possible to convert index.js to ES module?

### ISSUE THREAD

**Issue by Sharpiro** [AssemblyScript/wabt.js#8]
Making this small change will allow this module to be consumed as an ES module:
https://github.com/AssemblyScript/wabt.js/compare/master...Sharpiro:3c13807f1008e4451544a90fc108e8307cc5fc80

However I'm not sure if there is a way to adjust the syntax to keep in compatible with both ES modules as well as AMD/Common etc.

If it is not possible to have both in 1 file, could we add a secondary file that is built as an ES module?  index-es.js or index.mjs?

**Comment by Sharpiro** [comment]
do you think this would be an upstream wabt change as well?  this one is required for the other 2 issues i opened.

**Comment by dcodeIO** [comment]
Maybe, but changing this on their end would probably break existing users, so not sure. The alternative is to use custom build commands on the bot, one for ESM and one for UMD, with the latter just copying what's already there, and the former utilizing what Emscripten provides for ESM.

**Comment by dcodeIO** [comment]
Closing this issue as it seems this must be handled upstream :)
