### ISSUE TITLE
document must be declared to function in Deno

### ISSUE THREAD

**Issue by Sharpiro** [AssemblyScript/wabt.js#9]
https://github.com/Sharpiro/wabt.js/compare/3c13807f1008e4451544a90fc108e8307cc5fc80...Sharpiro:a71274e6ffbd38b58a0b6a2ea84c80336bc9c4a6

The above declaration for`document` was necessary to remove `document is not defined` error when running with [deno](https://github.com/denoland/deno)

basically there is a property access on `document` that only seems to be an issue in deno

**Comment by dcodeIO** [comment]
This looks like a change to be proposed upstream to [WABT itself](https://github.com/WebAssembly/wabt) (the wabt.js buildbot reuses its buildstep for JS), that might as well be related to how the file becomes compiled by [Emscripten](https://github.com/emscripten-core/emscripten).

**Comment by dcodeIO** [comment]
Closing this issue as it seems this must be handled upstream :)
